export const skills: Record<string, string[]> = {
  languages: ["C++", "Java", "Javascript", "TypeScript"],
  frontend: [
    "HTML",
    "CSS",
    "TailwindCSS",
    "React.js",
    "Redux & Recoil",
    "Next.js",
    "Framer Motion",
    "Jest & Vi-test.",
  ],
  backend: [
    "Node & Express JS",
    "Nest JS",
    "REST & RPC’s(G/T)",
    "Prisma ORM",
    "Web-rtc/sockets",
  ],
  DevOps: ["AWS S3, EC2, LAMBDA" , "Docker" , "OpenAPI" , "Git CI/CD"],
  DataBases: ["MongoDB", "SQL", "Redis"],
  Networking: [
    "LAN/WAN & TCP/IP ",
    "DHCP",
    "DNS",
    "Wireless ",
    "Reverse Proxies",
    "VPN's",
  ],
};
