export const skills: Record<string, string[]> = {
  languages: ["C++", "Python", "Javascript", "TypeScript"],
  frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "TailwindCSS",
    "React.js",
    "Redux & Recoil",
    "Next.js",
    "Framer Motion",
  ],
  backend: [
    "Node JS",
    "Express JS",
    "Nest JS",
    "Django",
    "FastAPI",
    "REST & RPC’s(G/T)",
    "ORM's",
    "Web-rtc/sockets",
  ],
  Testing: ["Jest", "Postman", "Puppeteer"],
  DevOps: [
    "AWS S3, EC2, LAMBDA",
    "Docker",
    "K8s",
    "OpenAPI",
    "Git CI/CD",
  ],
  DataBases: ["MongoDB", "SQL", "Redis", "PostgreSQL"],
  Networking: [
    "LAN/WAN & TCP/IP ",
    "DHCP",
    "DNS",
    "Wireless ",
    "Reverse Proxies",
    "VPN's",
  ],
};
